/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Material Design palette — "The Digital Atelier"
        'background': '#faf9f6',
        'surface': '#faf9f6',
        'surface-bright': '#faf9f6',
        'surface-dim': '#d6dbd5',
        'surface-variant': '#e0e4de',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f4f0',
        'surface-container': '#edeeea',
        'surface-container-high': '#e6e9e4',
        'surface-container-highest': '#e0e4de',
        'on-surface': '#2f3430',
        'on-surface-variant': '#5c605c',
        'on-background': '#2f3430',
        'inverse-surface': '#0d0f0d',
        'inverse-on-surface': '#9d9d9a',
        'primary': '#5f5e5c',
        'primary-dim': '#535250',
        'primary-container': '#e5e2de',
        'primary-fixed': '#e5e2de',
        'primary-fixed-dim': '#d7d4d0',
        'on-primary': '#faf7f3',
        'on-primary-fixed': '#403f3d',
        'on-primary-container': '#52524f',
        'secondary': '#6a5e45',
        'secondary-dim': '#5d5239',
        'secondary-container': '#f2e1c1',
        'secondary-fixed': '#f2e1c1',
        'secondary-fixed-dim': '#e3d2b3',
        'on-secondary': '#fff8f0',
        'on-secondary-container': '#5c5038',
        'on-secondary-fixed': '#493e27',
        'tertiary': '#5f5f5b',
        'tertiary-dim': '#535350',
        'tertiary-container': '#f5f3ee',
        'tertiary-fixed': '#f5f3ee',
        'tertiary-fixed-dim': '#e7e5e0',
        'on-tertiary': '#fbf9f3',
        'on-tertiary-container': '#5c5c58',
        'outline': '#777c77',
        'outline-variant': '#afb3ae',
        'surface-tint': '#5f5e5c',
        'inverse-primary': '#ffffff',
        'error': '#9e422c',
        'error-container': '#fe8b70',
        'on-error': '#fff7f6',
        'on-error-container': '#742410',
        // Legacy tokens (used by parked 3D components)
        'bg': '#F8F7F4',
        'bg-dark': '#0F0F0D',
        'text': '#1A1A18',
        'text-muted': '#6B6B67',
        'accent': '#C8B89A',
        'border': '#E2E0DA',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Georgia', 'serif'],
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
      letterSpacing: {
        label: '0.1em',
        display: '-0.04em',
      },
    },
  },
  plugins: [],
}
